### ISSUE TITLE
Use CRDT instead of Redis

### ISSUE THREAD

**Issue by nickpoorman** [amino/amino#2]
I could see this becoming extremely useful if it didn't require Redis first. [https://github.com/dominictarr/crdt](https://github.com/dominictarr/crdt) would be an excellent choice for removing the need for any kind of Redis server.

**Comment by carlos8f** [comment]
Interesting, I assume there would still be a central host/port (or list of them) to connect to to advertise or request service instances though. Also, why not use Redis?
